# Generated by Django 3.1.7 on 2021-03-24 17:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='paymentdetails',
            old_name='order_id',
            new_name='order',
        ),
        migrations.RenameField(
            model_name='paymentdetails',
            old_name='user_id',
            new_name='user',
        ),
    ]
