# Generated by Django 3.1.7 on 2021-03-25 04:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0002_doctor'),
        ('prescribed_history', '0002_auto_20210324_2353'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prescribedhistory',
            name='doctor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='doctor.doctor'),
        ),
    ]
