# Generated by Django 3.1.7 on 2021-03-30 14:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('prescribed_history', '0004_contactdetails'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ContactDetails',
        ),
    ]
