# Generated by Django 3.1.7 on 2021-03-25 09:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_auto_20210324_2353'),
        ('medicine', '0002_auto_20210324_2353'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('employee_id', models.IntegerField(primary_key=True, serialize=False)),
                ('employee_name', models.TextField()),
                ('contact_number', models.IntegerField()),
                ('address', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='MedicineShop',
            fields=[
                ('shop_id', models.IntegerField(primary_key=True, serialize=False)),
                ('shop_name', models.TextField()),
                ('shop_email', models.TextField()),
                ('shop_location', models.TextField()),
            ],
        ),
        migrations.RenameModel(
            old_name='Medicines',
            new_name='Medicine',
        ),
        migrations.DeleteModel(
            name='MedicineShops',
        ),
        migrations.AddField(
            model_name='medicineshop',
            name='medicine',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='medicine.medicine'),
        ),
        migrations.AddField(
            model_name='employee',
            name='shop',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='medicine.medicineshop'),
        ),
    ]
