# Generated by Django 3.1.7 on 2021-03-28 09:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('medicine', '0003_auto_20210325_1554'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicinesupplier',
            name='medicineShop',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='medicine.medicineshop'),
        ),
    ]
