# Generated by Django 3.1.7 on 2021-03-31 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicine', '0004_medicinesupplier_medicineshop'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='profile_pic',
            field=models.ImageField(default='default.png', upload_to='profile_pictures'),
        ),
        migrations.AddField(
            model_name='medicine',
            name='medicine_pic',
            field=models.ImageField(default='default.png', upload_to='medicine_picture'),
        ),
    ]
