# Generated by Django 3.1.7 on 2021-03-31 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicine', '0006_medicine_strength'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicine',
            name='pack_size',
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
