# Generated by Django 3.1.7 on 2021-03-31 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicine', '0007_medicine_pack_size'),
    ]

    operations = [
        migrations.RenameField(
            model_name='medicine',
            old_name='price',
            new_name='price_BDT',
        ),
        migrations.AlterField(
            model_name='medicine',
            name='company_name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='medicine',
            name='medicine_name',
            field=models.CharField(max_length=50),
        ),
    ]
