# Generated by Django 3.1.7 on 2021-03-31 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicine', '0008_auto_20210331_1946'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicine',
            name='price_BDT',
            field=models.FloatField(),
        ),
    ]
