# Generated by Django 3.1.7 on 2021-03-31 15:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('medicine', '0009_auto_20210331_1949'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='medicineshop',
            name='medicine',
        ),
        migrations.CreateModel(
            name='StoreMedicine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('medicine', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='medicine.medicine')),
                ('shop', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='medicine.medicineshop')),
            ],
        ),
    ]
