# Generated by Django 3.1.7 on 2021-03-30 11:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_auto_20210330_1734'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Contact',
        ),
    ]
