# Generated by Django 3.1.7 on 2021-03-30 14:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_contact'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Contact',
            new_name='UserContactDetails',
        ),
    ]
