# Generated by Django 3.1.7 on 2021-03-31 03:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0010_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='address',
            field=models.CharField(max_length=100),
        ),
    ]
