# Generated by Django 3.1.7 on 2021-04-11 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0014_appointment_applyappointmentdate'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='address',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='appointment',
            name='phone',
            field=models.CharField(default='', max_length=14),
        ),
    ]
