# Generated by Django 3.1.7 on 2021-04-11 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0015_auto_20210411_1531'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='description',
            field=models.TextField(default='', max_length=500),
        ),
    ]
