# Generated by Django 3.1.7 on 2021-03-24 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Doctors',
            fields=[
                ('doctor_id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.TextField()),
                ('email', models.TextField()),
                ('contact_number', models.IntegerField()),
                ('specialized', models.CharField(max_length=3)),
                ('schedule', models.CharField(max_length=15)),
                ('address', models.TextField()),
            ],
        ),
    ]
