# Generated by Django 3.1.7 on 2021-03-25 04:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('doctor_id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=30)),
                ('user_name', models.CharField(max_length=20)),
                ('email', models.CharField(max_length=25)),
                ('contact_number', models.IntegerField(max_length=11)),
                ('specialized', models.CharField(max_length=3)),
                ('schedule', models.CharField(max_length=15)),
                ('address', models.TextField()),
            ],
        ),
    ]
