# Generated by Django 3.1.7 on 2021-03-25 04:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0002_doctor'),
        ('prescribed_history', '0003_auto_20210325_1036'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Doctors',
        ),
    ]
