# Generated by Django 3.1.7 on 2021-03-31 16:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0005_auto_20210331_1531'),
    ]

    operations = [
        migrations.RenameField(
            model_name='doctor',
            old_name='specialized',
            new_name='specialist',
        ),
        migrations.RemoveField(
            model_name='doctor',
            name='department',
        ),
    ]
